language: elixir
elixir:
  - 1.10
otp_release:
  - 23.0
env:
  MIX_ENV=test
script:
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash) # send coverage report
cache:
  directories:
    - _build
    - deps
